SportsStore/SportsStore.WebUI/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Models {
	public class CartIndexViewModel {
		public Cart Cart { get; set; }
		public string ReturnUrl { get; set; }
	}
}

SportsStore/SportsStore.WebUI/Models/PagingInfo.cs
using System;
namespace SportsStore.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

SportsStore/SportsStore.WebUI/Models/ProductsListViewModel.cs
using System.Collections.Generic;
using SportsStore.Domain.Entities;
namespace SportsStore.WebUI.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

SportsStore/SportsStore.WebUI/Controllers/CartController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers {

	public class CartController : Controller {
		private IProductRepository repository;

		public CartController(IProductRepository repo) {
			repository = repo;
		}

		public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl) {
			Product product = repository.Products
				.FirstOrDefault(p => p.ProductID == productId);

			if (product != null) {
				cart.AddItem(product, 1);
			}
			return RedirectToAction("Index", new { returnUrl });
		}

		public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl) {
			Product product = repository.Products
				.FirstOrDefault(p => p.ProductID == productId);

			if (product != null) {
				cart.RemoveLine(product);
			}
			return RedirectToAction("Index", new { returnUrl });
		}

		private Cart GetCart() {

			Cart cart = (Cart)Session["Cart"];
			if (cart == null) {
				cart = new Cart();
				Session["Cart"] = cart;
			}
			return cart;
		}

		public ViewResult Index(string returnUrl) {
			return View(new CartIndexViewModel {
				Cart = GetCart(),
				ReturnUrl = returnUrl
			});
		}

        public ViewResult Index(Cart cart, string p) {
            throw new System.NotImplementedException();
        }

        public ViewResult Summary(Cart cart) {
            return View(cart);
        }
    }
}

SportsStore/SportsStore.WebUI/Controllers/NavController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.WebUI.Models;
namespace SportsStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;
        public NavController(IProductRepository repo)
        {
            repository = repo;
        }
        public ViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x);
            return View(categories);
        }
    }
}

SportsStore/SportsStore.WebUI/Controllers/ProductController.cs
using System.Linq;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers {

    public class ProductController : Controller {

        public int PageSize = 4;

        private IProductRepository repository;

        public ProductController(IProductRepository productRepository) {

            repository = productRepository;
        }

        public ViewResult List(string category, int page = 1)
        {
            ProductsListViewModel viewModel = new ProductsListViewModel
            {
                Products = repository.Products
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(p => p.ProductID)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                        repository.Products.Count() :
                        repository.Products.Where(e => e.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(viewModel);
        }
    }
}

SportsStore/SportsStore.WebUI/Views/Cart/Index.cshtml
@model SportsStore.WebUI.Models.CartIndexViewModel 
@{ 
    ViewBag.Title = "Sports Store: Your Cart"; 
}
<h2>
	Your cart</h2>
<!-- Detta är ingen Html-kurs så jag bjuder på lite Html-godis gratis :) -->
<table width="90%" align="center">
	<thead>
		<tr>
			<th align="center">
				Quantity
			</th>
			<th align="left">
				Item
			</th>
			<th align="right">
				Price
			</th>
			<th align="right">
				Subtotal
			</th>
            <th align="right">
				Remove from cart
			</th>
		</tr>
	</thead>
	<tbody>
		@foreach(var line in Model.Cart.Lines) { 
			<tr>
				<td align="center">@line.Quantity
				</td>
				<td align="left">@line.Product.Name
				</td>
				<td align="right">@line.Product.Price.ToString("c")
				</td>
				<td align="right">@((line.Quantity * line.Product.Price).ToString("c"))
				</td>
                <td align="right">@((line.Quantity * line.Product.Price).ToString("c"))</td> <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart")) {
                        @Html.Hidden("ProductId", line.Product.ProductID)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="actionButtons" type="submit" value="Remove" />
                    }
                </td>
			</tr> 
        }
	</tbody>
	<tfoot>
		<tr>
			<td colspan="3" align="right">
				Total:
			</td>
			<td align="right">
				@Model.Cart.ComputeTotalValue().ToString("c")
			</td>
            <td align="right">
				
			</td>
		</tr>
	</tfoot>
</table>
<p align="center" class="actionButtons">
	<a href="@Model.ReturnUrl">Continue shopping</a>
</p>

SportsStore/SportsStore.WebUI/Views/Cart/Summary.cshtml
@model SportsStore.Domain.Entities.Cart
@{
    Layout = null;
}
<div id="cart">
    <span class="caption">
        <b>Your cart:</b>
        @Model.Lines.Sum(x => x.Quantity) item(s),
        @Model.ComputeTotalValue().ToString("c")
    </span>
    @Html.ActionLink("Checkout", "Index", "Cart",
        new { returnUrl = Request.Url.PathAndQuery }, null)
</div>

SportsStore/SportsStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@{
Layout = null;
}
@Html.ActionLink("Home", "List", "Product")
@foreach (var link in Model) {
    @Html.RouteLink(link, 
        new {
            controller = "Product",
            action = "List",
            category = link,
            page = 1
        },
        new {
            @class = link == ViewBag.SelectedCategory ? "selected" : null
        }
    )
}

SportsStore/SportsStore.WebUI/Views/Product/List.cshtml
@model SportsStore.WebUI.Models.ProductsListViewModel

@{
    ViewBag.Title = "Products";
}

@foreach (var p in Model.Products) {
    Html.RenderPartial("ProductSummary", p);
}

<div class="pager">
   @Html.PageLinks(Model.PagingInfo, x => Url.Action("List",
               new { page = x, category = Model.CurrentCategory }))
    
</div>

SportsStore/SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

<div class="item">
    <h3>@Model.Name</h3>
    @Model.Description

	@using(Html.BeginForm("AddToCart", "Cart")) { 
		@Html.HiddenFor(x => x.ProductID) 
		@Html.Hidden("returnUrl", Request.Url.PathAndQuery) 
		<input type="submit" value="+ Add to cart" /> 
    }

    <h4>@Model.Price.ToString("c")</h4>
</div>


SportsStore/SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")"
type="text/javascript"></script>
</head>
<body>
    <div id="header">
        @{Html.RenderAction("Summary", "Cart");}
        <div class="title">SPORTS STORE</div>
     </div>
     <div id="categories">
        @{ Html.RenderAction("Menu", "Nav"); }
     </div>
     <div id="content">
        @RenderBody()
</div>
</body>
</html>